// This file is generated by Prismic local builder. Update with care!

export { default as CtaBanner } from './CtaBanner'
export { default as MainHero } from './MainHero'
export { default as MySlice } from './MySlice'
export { default as Services } from './Services'
export { default as TextBlock } from './TextBlock'
export { default as TextWithImageBlock } from './TextWithImageBlock'
